exceptions:try_with_catch_arg
